services:
  idf:
    image: espressif/idf:v5.5
    container_name: idf
    hostname: idf
    privileged: true
    working_dir: /project
    environment:
      - HOME=/tmp
    volumes:
      - ./project:/project
    device:
      - /dev/ttyUSB0:rw
    # https://www.redhat.com/en/blog/files-devices-podman
    group_add:
      - keep-groups
    network_mode: host